---
apiVersion: v1
kind: Namespace
metadata:
  name: auto-chaosblade---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaosblade
  labels:
    name: chaosblade
  namespace: auto-chaosblade
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: chaosblade
  labels:
    name: chaosblade
rules:
  - apiGroups:
      - ''
    resources:
      - pods
      - pods/exec
      - services
      - endpoints
      - persistentvolumeclaims
      - persistentvolumes
      - events
      - configmaps
      - secrets
      - namespaces
      - nodes
    verbs:
      - "*"
  - apiGroups:
      - extensions
    resources:
      - deployments
      - daemonsets
      - replicasets
      - ingresses
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - "*"
  - apiGroups:
      - chaosblade.io
    resources:
      - chaosblades
      - chaosblades/status
    verbs:
      - "*"
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs: ["get","create","update","list","watch","patch"]
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
      - certificatesigningrequests/approval
    verbs: ["get","create","update","list","watch","patch"]


---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: chaosblade
  labels:
    name: chaosblade
roleRef:
  kind: ClusterRole
  name: chaosblade
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: chaosblade
    namespace: auto-chaosblade
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: chaosblades.chaosblade.io
spec:
  group: chaosblade.io
  names:
    kind: ChaosBlade
    listKind: ChaosBladeList
    plural: chaosblades
    singular: chaosblade
    shortNames: [blade]
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            experiments:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                properties:
                  action:
                    description: Action is the experiment scenario of the target,
                      such as delay, load
                    type: string
                  desc:
                    description: Desc is the experiment description
                    type: string
                  matchers:
                    description: Matchers is the experiment rules
                    items:
                      properties:
                        name:
                          description: Name is the name of flag
                          type: string
                        value:
                          description: 'TODO: Temporarily defined as an array for
                            all flags Value is the value of flag'
                          items:
                            type: string
                          type: array
                      required:
                      - name
                      - value
                      type: object
                    type: array
                  scope:
                    description: Scope is the area of the experiments, currently support
                      node, pod and container
                    type: string
                  target:
                    description: Target is the experiment target, such as cpu, network
                    type: string
                required:
                - scope
                - target
                - action
                type: object
              type: array
          required:
          - experiments
          type: object
        status:
          properties:
            expStatuses:
              description: 'Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                properties:
                  action:
                    type: string
                  error:
                    type: string
                  resStatuses:
                    description: ResStatuses is the details of the experiment
                    items:
                      properties:
                        error:
                          description: experiment error
                          type: string
                        id:
                          description: experiment uid in chaosblade
                          type: string
                        kind:
                          description: Kind
                          type: string
                        name:
                          description: resource name
                          type: string
                        nodeName:
                          description: NodeName
                          type: string
                        state:
                          description: experiment state
                          type: string
                        success:
                          description: success
                          type: boolean
                        uid:
                          description: resource uid
                          type: string
                      required:
                      - state
                      - kind
                      - success
                      type: object
                    type: array
                  scope:
                    description: experiment scope for cache
                    type: string
                  state:
                    description: State is used to describe the experiment result
                    type: string
                  success:
                    description: Success is used to judge the experiment result
                    type: boolean
                  target:
                    type: string
                required:
                - scope
                - target
                - action
                - success
                - state
                type: object
              type: array
            phase:
              description: Phase indicates the state of the experiment   Initial ->
                Running -> Updating -> Destroying -> Destroyed
              type: string
          required:
          - expStatuses
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
--- 
apiVersion: v1
kind: Service
metadata:
  name: chaosblade-webhook-server
  namespace: auto-chaosblade
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    name: chaosblade-operator
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaosblade-operator
  namespace: auto-chaosblade
spec:
  replicas: 1
  selector:
    matchLabels:
      name: chaosblade-operator
  template:
    metadata:
      labels:
        name: chaosblade-operator
    spec:
      serviceAccountName: chaosblade
      containers:
        - name: chaosblade-operator
          # Replace this with the built image name
          image: thub.autohome.com.cn/ops-cache/chaosblade-operator:0.9.0
          command: ["chaosblade-operator"]
          args:
            - --chaosblade-version=0.9.0
            - --chaosblade-image-repository=thub.autohome.com.cn/ops-cache/chaosblade-tool
            - --chaosblade-image-pull-policy=Always
            - --webhook-enable
            - --daemonset-enable
            - --remove-blade-interval=72h
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "chaosblade-operator"
          ports:
            - containerPort: 9443
              protocol: TCP
          resources:
            limits:
              cpu: "600m"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "1Gi"
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: chaosblade-webhook-server-cert
