--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaosblade-operator
  namespace: auto-chaosblade
spec:
  replicas: 1
  selector:
    matchLabels:
      name: chaosblade-operator
  template:
    metadata:
      labels:
        name: chaosblade-operator
    spec:
      serviceAccountName: chaosblade
      containers:
        - name: chaosblade-operator
          # Replace this with the built image name
          image: thub.autohome.com.cn/ops-cache/chaosblade-operator:0.9.0
          command: ["chaosblade-operator"]
          args:
            - --chaosblade-version=0.9.0
            - --chaosblade-image-repository=thub.autohome.com.cn/ops-cache/chaosblade-tool
            - --chaosblade-image-pull-policy=Always
            - --webhook-enable
            - --daemonset-enable
            - --remove-blade-interval=72h
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "chaosblade-operator"
          ports:
            - containerPort: 9443
              protocol: TCP
          resources:
            limits:
              cpu: "600m"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "1Gi"
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: chaosblade-webhook-server-cert
